# Generated by Django 4.2.4 on 2023-08-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriatarea',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='tarea',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
    ]
